spring.application.name=employee-leave-management
server.port=8080

spring.datasource.url=jdbc:mysql://${MYSQLHOST:127.0.0.1}:${MYSQLPORT:3306}/${MYSQLDATABASE:employee_leave_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Admin@1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change-this-secret-key-to-a-long-random-value-for-production-use-123456789
app.jwt.expiration-ms=86400000
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Swagger UI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha




