import {useEffect,useState} from 'react';import {Pencil,Trash2,Plus,Search,Users} from 'lucide-react';import {employeeApi,departmentApi} from '../services/api';
import toast from 'react-hot-toast';
const empty={name:'',email:'',phone:'',password:'',role:'EMPLOYEE',departmentId:''};
export default function Employees(){const [items,setItems]=useState([]),[departments,setDepartments]=useState([]),[search,setSearch]=useState(''),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[open,setOpen]=useState(false);const load=async()=>{try{const [e,d]=await Promise.all([employeeApi.getAll(search),departmentApi.getAll()]);setItems(e.data);setDepartments(d.data)}catch(err){toast.error(err.response?.data?.error||'Unable to load employees.')}};useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search]);const save=async e=>{e.preventDefault();toast.error('');try{const payload={...form,departmentId:form.departmentId?Number(form.departmentId):null};if(!payload.password)delete payload.password;editing?await employeeApi.update(editing,payload):await employeeApi.create(payload);setOpen(false);setEditing(null);setForm(empty);
toast.success('Employee saved successfully!');load()}catch(err){toast.error(err.response?.data?.error||'Unable to save employee.')}};const remove=async id=>{if(!confirm('Remove this employee?'))return;try{await employeeApi.remove(id);
toast.success('Employee deleted!');load()}catch(err){toast.error(err.response?.data?.error||'Unable to remove employee.')}};return <div className="page"><div className="hero"><div><span className="eyebrow">PEOPLE DIRECTORY</span><h2>Employees</h2><p>Maintain employee access, contact details and department assignments.</p></div><button className="primary-btn" onClick={()=>{setEditing(null);setForm(empty);
toast.success('Employee saved successfully!');setOpen(true)}}><Plus size={16}/> Add employee</button></div><div className="toolbar-row"><div className="search-box"><Search size={16}/><input placeholder="Search name or email" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="result-count">{items.length} employees</span></div><div className="table-card"><table><thead><tr><th>Employee</th><th>Contact</th><th>Department</th><th>Role</th><th>Actions</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td><div className="table-person"><div className="avatar small">{e.name?.slice(0,1)}</div><div><strong>{e.name}</strong><small>{e.email}</small></div></div></td><td>{e.phone||'—'}</td><td>{e.department?.name||'Unassigned'}</td><td><span className="role-badge">{e.role}</span></td><td><div className="actions"><button onClick={()=>{setEditing(e.id);setForm({name:e.name,email:e.email,phone:e.phone||'',password:'',role:e.role,departmentId:e.department?.id||''});setOpen(true)}}><Pencil size={15}/></button><button onClick={()=>remove(e.id)}><Trash2 size={15}/></button></div></td></tr>)}{!items.length&&<tr><td className="empty" colSpan="5"><Users size={24}/>No employees found.</td></tr>}</tbody></table></div>{open&&<div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><span className="eyebrow">PEOPLE ADMINISTRATION</span><h3>{editing?'Edit employee':'Add employee'}</h3></div><button className="icon-btn" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save}><div className="form-row"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="form-row"><label>Password <span className="optional">{editing?'(blank = unchanged)':''}</span><input required={!editing} minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>EMPLOYEE</option><option>HR</option></select></label></div><label>Department<select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Unassigned</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="form-actions"><button className="primary-btn">{editing?'Save changes':'Create employee'}</button><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}</div>}



